name: movie_info
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  better_player: ^0.0.73
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  dartx: ^0.7.1
  dartz: ^0.10.0
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  http: ^0.13.3
  injectable: ^1.5.0
  json_annotation: ^4.1.0
  logger: ^1.0.0
  photo_view: ^0.12.0
  pretty_dio_logger: ^1.1.1
  provider: ^6.0.0
  retrofit: ^2.0.1
  rxdart: ^0.27.1
  time: ^2.0.0

dev_dependencies:
  auto_route: ^2.3.0
  auto_route_generator: ^2.3.0
  build_runner: ^2.1.1
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  injectable_generator: ^1.5.0
  json_serializable: ^5.0.0
  retrofit_generator: ^2.0.1+1

dependency_overrides:
  meta: ^1.7.0

flutter:

  uses-material-design: true

flutter_app_name:
  name: "Movie Info"

scripts: derry.yaml
