// Generated by https://quicktype.io

import 'package:freezed_annotation/freezed_annotation.dart';
part 'language.g.dart';

@JsonSerializable(fieldRename: FieldRename.snake)
class Language {
  String englishName;
  @JsonKey(name: 'iso_639_1')
  String iso6391;
  String name;

  Language({
    this.englishName = '',
    this.iso6391 = '',
    this.name = '',
  });

  factory Language.fromJson(Map<String, dynamic> json) =>
      _$LanguageFromJson(json);
  Map<String, dynamic> toJson() => _$LanguageToJson(this);
}
