part of '../remote_repository.dart';

mixin DiscoverPart {
  @GET('/discover/movie')
  Future<PageResult<Movie>> discoverMovie({
    @Query('region') String? region,
    @Query('sort_by') String? sortBy,
    @Query('certification_country') String? certificationCountry,
    @Query('certification') String? certification,
    @Query('certification.lte') String? certificationLte,
    @Query('certification.gte') String? certificationGte,
    @Query('include_adult') bool? includeAdult,
    @Query('include_video') bool? includeVideo,
    @Query('page') int? page,
    @Query('primary_release_year') int? primaryReleaseYear,
    @Query('primary_release_date.gte') String? primaryReleaseDateGte,
    @Query('primary_release_date.lte') String? primaryReleaseDateLte,
    @Query('release_date.gte') String? releaseDateGte,
    @Query('release_date.lte') String? releaseDateLte,
    @Query('with_release_type') int? withReleaseType,
    @Query('year') int? year,
    @Query('vote_count.gte') int? voteCountGte,
    @Query('vote_count.lte') int? voteCountLte,
    @Query('vote_average.gte') num? voteAverageGte,
    @Query('vote_average.lte') num? voteAverageLte,
    @Query('with_cast') String? withCast,
    @Query('with_crew') String? withCrew,
    @Query('with_people') String? withPeople,
    @Query('with_companies') String? withCompanies,
    @Query('with_genres') String? withGenres,
    @Query('without_genres') String? withoutGenres,
    @Query('with_keywords') String? withKeywords,
    @Query('without_keywords') String? withoutKeywords,
    @Query('with_runtime.gte') int? withRuntimeGte,
    @Query('with_runtime.lte') int? withRuntimeLte,
    @Query('with_original_language') String? withOriginalLanguage,
    @Query('with_watch_providers') String? withWatchProviders,
    @Query('watch_region') String? watchRegion,
    @Query('with_watch_monetization_types') String? withWatchMonetizationTypes,
  });

  @GET('/discover/tv')
  Future<PageResult<TV>> discoverTV({
    @Query('sort_by') String? sortBy,
    @Query('air_date.gte') String? airDateGte,
    @Query('air_date.lte') String? airDateLte,
    @Query('first_air_date.gte') String? firstAirDateGte,
    @Query('first_air_date.lte') String? firstAirDateLte,
    @Query('first_air_date_year') int? firstAirDateYear,
    @Query('page') int? page,
    @Query('timezone') String? timezone,
    @Query('vote_average.gte') num? voteAverageGte,
    @Query('vote_count.gte') int? voteCountGte,
    @Query('with_genres') String? withGenres,
    @Query('with_networks') String? withNetworks,
    @Query('without_genres') String? withoutGenres,
    @Query('with_runtime.gte') int? withRuntimeGte,
    @Query('with_runtime.lte') int? withRuntimeLte,
    @Query('include_null_first_air_dates') bool? includeNullFirstAirDates,
    @Query('with_original_language') String? withOriginalLanguage,
    @Query('without_keywords') String? withoutKeywords,
    @Query('screened_theatrically') bool? screenedTheatrically,
    @Query('with_companies') String? withCompanies,
    @Query('with_keywords') String? withKeywords,
    @Query('with_watch_providers') String? withWatchProviders,
    @Query('watch_region') String? watchRegion,
    @Query('with_watch_monetization_types') String? withWatchMonetizationTypes,
  });
}
